### ISSUE TITLE
能开个分支改成跟geoip可以通过变量获取值么？

### ISSUE THREAD

**Issue by xianhuawei** [detailyang/ngx_http_ipip_module#2]
有个需求是通过ipip获取ip对应的位置信息记录到日志 以便后续分析

类似 http://nginx.org/en/docs/http/ngx_http_geoip_module.html 中的

$geoip_area_code
telephone area code (US only).
This variable may contain outdated information since the corresponding database field is deprecated.
$geoip_city_continent_code
two-letter continent code, for example, “EU”, “NA”.
$geoip_city_country_code
two-letter country code, for example, “RU”, “US”.
$geoip_city_country_code3
three-letter country code, for example, “RUS”, “USA”.
$geoip_city_country_name
country name, for example, “Russian Federation”, “United States”.

能否开新的分支把解析出来的：
      "中国",                // 国家
      "天津",                // 省会或直辖市（国内）
      "天津",                // 地区或城市 （国内）
      "",                   // 学校或单位 （国内）
      "鹏博士",              // 运营商字段（只有购买了带有运营商版本的数据库才会有）
      "39.128399",          // 纬度     （每日版本提供）
      "117.185112",         // 经度     （每日版本提供）
      "Asia/Shanghai",      // 时区一, 可能不存在  （每日版本提供）
      "UTC+8",              // 时区二, 可能不存在  （每日版本提供）
      "120000",             // 中国行政区划代码    （每日版本提供）
      "86",                 // 国际电话代码        （每日版本提供）
      "CN",                 // 国家二位代码        （每日版本提供）
      "AP"                  // 世界大洲代码        （每日版本提供）

这几个变成类似上面的可以记录到access_log的变量呢？
谢谢啦

**Comment by detailyang** [comment]
Hello.
本仓库已经迁移至公司项目维护 [youzan/ngx_http_ipip_module](https://github.com/youzan/ngx_http_ipip_module)，这里已不在维护，麻烦在那边提一下 issue。
